# Site settings
title: Willem-Merwe Joubert Website
description: My Personalised Website.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "Willem-Merwe.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Willem-Merwe Joubert
user_description: I'm a Student living in the Beautiful City of Cape Town, South Africa. I'm in my second year of studies and working hard towards completing my BSc in Computing and becoming a Software Developer with an keen interest in Game and Web Development.
user_title: Software Developer
email: merwejoubert@gmail.com
github_username: Willem-Merwe
gplus_username: Merwe Joubert

# Google-analytics
google-analytics:
  id: "UA-118795493-1"

exclude: ['package.json', 'src' , 'node_modules']

theme: jekyll-theme-dinky